services:
  db:
    image: postgres:17.2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  zookeeper:
    image: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: &kafka_image confluentinc/cp-kafka:7.4.1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://:29092,PLAINTEXT_HOST://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT

  kafka-init:
    image: *kafka_image
    depends_on:
      - kafka
    command: |
      bash -c "
      while ! nc -z kafka 29092; do
        echo 'Waiting for Kafka...';
        sleep 5;
      done;
      kafka-topics --create --topic image --if-not-exists --bootstrap-server kafka:29092 --replication-factor 1 --partitions 1;
      kafka-topics --create --topic slideshow --if-not-exists --bootstrap-server kafka:29092 --replication-factor 1 --partitions 1;
      "
#  kafka-console-consumer.sh --bootstrap-server localhost:29092 --topic my-test-topic --from-beginning